

export const FETCH_TOTAL_LISTS = 'FETCH_TOTAL_LISTS';

export const FETCH_PREMIUM_LISTS = 'FETCH_PREMIUM_LISTS';
export const UPDATE_PREMIUM_LIST = 'UPDATE_PREMIUM_LIST';

export const FETCH_CONTENT_LIST = 'FETCH_CONTENT_LIST';


export const NEW_BANNER = 'NEW_BANNER';
export const DELETE_BANNER = 'DELETE_BANNER';
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST';
export const FETCH_BANNER = 'FETCH_BANNER';

export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
export const SAVE_ORDER_LIST = 'SAVE_ORDER_LIST';
